name: Swiss build

on: [push, pull_request]

jobs:
  build:
    name: Build Swiss
    runs-on: ubuntu-latest
    container: ghcr.io/extremscorner/libogc2:latest

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends -t bookworm-backports 7zip gcc gcc-mingw-w64-i686 libc6-dev libc6-i386 xorriso

    - name: Checkout Swiss
      uses: actions/checkout@main
      with:
        path: swiss
        fetch-depth: 0
        submodules: true

    - name: Build Swiss artifacts
      run: make
      working-directory: swiss

    - name: Upload Swiss artifacts
      uses: actions/upload-artifact@main
      with:
        name: swiss-gc
        path: swiss/swiss_r*/*
